### ISSUE TITLE
Use CDK Parameters for all params required on the stack

### ISSUE THREAD

**Issue by donnieprakoso** [ttirtawi/cdk-multiregion-r53#1]
Currently all params are required to be manually changed (marked with double asterisks **)

```
const region1 = new regionalStack(app, 'region1', {
  stackName: "region1",
  **keyPair: "tirtawid-dev",**
  cidr: "172.11.0.0/24",
  failoverRole: "PRIMARY",
  failoverRecord: failoverRecord,
  domain,
  **subdomain: 'region1',**
  **env: { account: '452922823873', region: 'ap-southeast-1' }**
});
```

Requesting to change these params into CDK parameters, so we can easily adjust and use the stack.

**Comment by ttirtawi** [comment]
Modify the code using context instead of CDK parameters as some logic (lookup Route53 hosted zone) require the value to be available during runtime.
